### ISSUE TITLE
May I get the link of the dataset?

### ISSUE THREAD

**Issue by chaneyddtt** [luminxu/Pose-for-Everything#1]
Hi @luminxu,thanks for the great work. May I know when you are going to release the dataset?

**Comment by luminxu** [comment]
We are working on legal affairs right now. We will provide the access after getting permission.

**Comment by chaneyddtt** [comment]
Thanks for your kind reply. May I know how long it will take roughly?

**Comment by jin-s13** [comment]
Because of legal reasons, we can not directly provide the images. 
But you may follow this [guide](https://github.com/luminxu/Pose-for-Everything/blob/main/mp100/README.md) to prepare the data.
