### ISSUE TITLE
Questions about the single-dataset (COCO) training.

### ISSUE THREAD

**Issue by Gengzigang** [luminxu/Pose-for-Everything#12]
Hi, thanks for sharing the code for your amazing work. From my understanding, training only using the COCO dataset is just a special case of the proposed method. I would like to ask if you have tried it.

**Comment by jin-s13** [comment]
Training on a specific human keypoint dataset (e.g. COCO) is not our major target. 
We have included experiments about human keypoints in Table4, but it only uses a small number of human data.
