### ISSUE TITLE
Question about Vinegar Fly Dataset

### ISSUE THREAD

**Issue by worklikerlei** [luminxu/Pose-for-Everything#15]
How the h5 file in this Vinegar Fly Dataset is converted into pictures. The name cannot match your mp100 dataset after I convert. Thank you very much!

**Comment by jin-s13** [comment]
We used this https://github.com/open-mmlab/mmpose/blob/master/tools/dataset/parse_deepposekit_dataset.py

**Comment by worklikerlei** [comment]
> We used this https://github.com/open-mmlab/mmpose/blob/master/tools/dataset/parse_deepposekit_dataset.py

Yeah, thank you for your response.
