### ISSUE TITLE
Guidance for fly_body, locust_body

### ISSUE THREAD

**Issue by kltrock** [luminxu/Pose-for-Everything#2]
Following your guidance, fly_body and locust_body are collected from the same [repo](https://github.com/jgraving/DeepPoseKit-Data). However, the data is in HDF5 files. Could you please provide more details on how to prepare data for these two categories? Thank you very much.

**Comment by luminxu** [comment]
For these two categories, please follow [mmpose](https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/2d_animal_keypoint.md) for data preparation.

**Comment by kltrock** [comment]
Thank you for your quick response
