### ISSUE TITLE
ATRW instead of AFLW?

### ISSUE THREAD

**Issue by kltrock** [luminxu/Pose-for-Everything#4]
In your guidance, amur_tiger_body is collected from [AFLW](https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/). However, AFLW is human face dataset. I think the correct dataset is [ATRW](https://arxiv.org/abs/1906.05586).

**Comment by luminxu** [comment]
Sorry for the confusion. In fact, ``amur_tiger_body`` is indeed collected from [AFLW](https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/). We choose to include two human face categories in our dataset finally to test the model generalization ability on different keypoint definitions.

We have reorganize a clean version of MP-100 dataset, but directly releasing it will face legal risks. We are still working on it. If it does not work, we will refine the annotations and provide more detailed guidance.

**Comment by Junhojuno** [comment]
> Sorry for the confusion. In fact, `amur_tiger_body` is indeed collected from [AFLW](https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/). We choose to include two human face categories in our dataset finally to test the model generalization ability on different keypoint definitions.
> 
> We have reorganize a clean version of MP-100 dataset, but directly releasing it will face legal risks. We are still working on it. If it does not work, we will refine the annotations and provide more detailed guidance.

you mean, `amur_tiger_body` is an annotation of human face which is different from `300W`, `amur_tiger_body` is just named to distinguish them, nothing to do with the name as it is. do I understand right?

**Comment by oopsRookie** [comment]
> > Sorry for the confusion. In fact, `amur_tiger_body` is indeed collected from [AFLW](https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/). We choose to include two human face categories in our dataset finally to test the model generalization ability on different keypoint definitions.
> > We have reorganize a clean version of MP-100 dataset, but directly releasing it will face legal risks. We are still working on it. If it does not work, we will refine the annotations and provide more detailed guidance.
> 
> you mean, `amur_tiger_body` is an annotation of human face which is different from `300W`, `amur_tiger_body` is just named to distinguish them, nothing to do with the name as it is. do I understand right?

Same question here
