### ISSUE TITLE
Inference the model

### ISSUE THREAD

**Issue by PhanThanhTrung** [luminxu/Pose-for-Everything#8]
After training, I got the POMNet weight saved in `work_dirs`. I want to use it to infer with my own test images, but this model always takes the support and query images in the inference time. So how I can test this with a single image?

**Comment by luminxu** [comment]
POMNet can not test a single query image without the support image. The inference process is similar to training, except for the MSE loss supervision. The support image provides the keypoint definition to be predicted, so it is needed.

**Comment by PhanThanhTrung** [comment]
Yeah, thank you for your response.
